### ISSUE TITLE
Various scraping accuracy issues

### ISSUE THREAD

**Issue by bakugo** [miyachan/torako#9] opened 2021-03-10 17:27 UTC
* When a thread gets deleted, every post in it is also marked as deleted (only the OP should be marked as deleted)
* When a thread is archived, it gets marked as closed (the closed value should be ignored when a thread is archived)
* Unique IP count is always saved as 1

**Comment by bakugo** [comment] 2021-03-22 04:38
More:
* Sticky/closed threads are not saved as sticky/closed if they get unstickied/unclosed before dying

**Comment by miyachan** [comment] 2021-03-22 05:09
> When a thread gets deleted, every post in it is also marked as deleted (only the OP should be marked as deleted)

This happens because we treat every post individually, we check every individual post in the cache against what the api returns. If the post can no longer be found in the API we mark it as deleted. We need to skip the deletion mark if the thread_no is also deleted. (https://github.com/miyachan/torako/blob/9eecad4dd6b650c3cd1ea37de4bac35f55910c0a/src/imageboard/board_stream.rs#L597)

> When a thread is archived, it gets marked as closed (the closed value should be ignored when a thread is archived)

Not sure how to handle this yet as currently we pass the _current_ representation of the thread to downstream engines, which may not know if the thread was `closed` before hand (if we assume `closed` threads are not really `closed` if they are archived, then we might *unclose* some threads

> Unique IP count is always saved as 1

Can't seem to reproduce?

<img width="1203" alt="Screen Shot 2021-03-21 at 10 08 21 PM" src="https://user-images.githubusercontent.com/5410198/111943111-f594e900-8a91-11eb-9033-ad65e6053150.png">

> Sticky/closed threads are not saved as sticky/closed if they get unstickied/unclosed before dying

Is this Asagi behavior? Where sticky/closed threads are a set if the thread was sticked at any point.

**Comment by bakugo** [comment] 2021-03-22 05:39
>Not sure how to handle this yet as currently we pass the current representation of the thread to downstream engines, which may not know if the thread was closed before hand (if we assume closed threads are not really closed if they are archived, then we might unclose some threads

These are the problems that arise with too much abstraction, it's better to have a consistent thread state that is only updated when necessary instead instead of handling incoming data as-is. Regardless,

**Comment by bakugo** [comment] 2021-03-22 05:44
>Not sure how to handle this yet as currently we pass the current representation of the thread to downstream engines, which may not know if the thread was closed before hand (if we assume closed threads are not really closed if they are archived, then we might unclose some threads

This is one of the problems that comes with too much abstraction, it would be more convenient to have a consistent thread state that only changes when necessary instead of handling incoming data as-is. That said this isn't hard to handle, the closed value should only be updated when it becomes 1 (asagi does `closed = (%s OR closed)`), and it should be considered 0 when archived is 1.

>Can't seem to reproduce?

I noticed these issues while observing archive.wakarimasen.moe, not sure how accurate it is to what the latest version of the scraper actually does.

>Is this Asagi behavior? Where sticky/closed threads are a set if the thread was sticked at any point.

Yes, and it's also common sense. Sticky threads are usually unstickied before dying, so without this behavior, that information is effectively lost. Like with closed, asagi uses `sticky = (%s OR sticky)` for this.

**Comment by miyachan** [comment] 2021-03-22 06:00
> This is one of the problems that comes with too much abstraction, it would be more convenient to have a consistent thread state that only changes when necessary instead of handling incoming data as-is.

I'm not sure the problem is too much abstraction here - in fact it seems like the opposite; Essentially what torako does is the scraper exposes a change stream. Naively changing the change stream involves *adding* an abstraction that filters out certain changes (a thread becoming unstickied).

> That said this isn't hard to handle, the closed value should only be updated when it becomes 1 (asagi does closed = (%s OR closed)), and it should be considered 0 when archived is 1.


> Like with closed, asagi uses sticky = (%s OR sticky) for this.

Ah fixing it in SQL makes sense, and is actually preferable here, and makes it easy, and the change stream doesn't need to get any smarter.

> Yes, and it's also common sense.

I thought this too, but where that breaks down is in trying to figure out how this behavior works with FoolFuuka. Admittedly this may be a problem with my understanding of FoolFuuka, but if you *don't* unsticky a thread after it dies, it remains "sticked" forever, and therefore ends up on page 1. When I originally did it this way wakarimasen's /a/ archive was broken as the first page was every sticked thread that every happened. 

Obviously there might be something wrong with my install as archived.moe doesn't show sticked threads (https://archived.moe/fit) while wakarimasen does (https://archive.wakarimasen.moe/fit/).

> I noticed these issues while observing archive.wakarimasen.moe, not sure how accurate it is to what the latest version of the scraper actually does.

No there actually is a bug here, I see it on some threads now.

**Comment by bakugo** [comment] 2021-03-22 06:05
>but if you don't unsticky a thread after it dies, it remains "sticked" forever, and therefore ends up on page 1.

That only happens if the sticky value is also set in the _threads table, which is not supposed to happen on archives, it should only be set in the posts table (the _threads table is used for sticky sorting)

**Comment by miyachan** [comment] 2021-03-22 06:59
Your bugs have been incorporated in 0.11.2, I will run it for a while on wakarimasen.moe before closing the issue.

**Comment by miyachan** [comment] 2021-03-29 21:45
> When a thread gets deleted, every post in it is also marked as deleted (only the OP should be marked as deleted)

Fixed, posts are no longer marked as deleted (https://archive.wakarimasen.moe/a/thread/219245480/#219245480)

> When a thread is archived, it gets marked as closed (the closed value should be ignored when a thread is archived)

Fixed, threads are no longer marked as archived (https://archive.wakarimasen.moe/a/thread/218681156/#218686645)

> Unique IP count is always saved as 1

Unique IP count now always updates

> Sticky/closed threads are not saved as sticky/closed if they get unstickied/unclosed before dying

Fixed for sticky threads on 0.11.2; Fixed for closed threads on master.

Thanks @bakugo

**Closed by miyachan** 2021-03-29 21:45 UTC
